---

# Installation de Wordpress
- name: Unzip WordPress
  unarchive:
    src: wordpress-5.3.2-fr_FR.zip
    dest: /tmp
    creates: /tmp/wordpress/wp-settings.php

- name: Create project folder
  file:
    dest: /var/www/book.example.com
    state: directory

- name: Copy WordPress files
  command: cp -a /tmp/wordpress/. /var/www/book.example.com
  args:
    creates: /var/www/book.example.com/wp-settings.php

# Creation de la base de donnee de wordpress
- name: Create WordPress MySQL database
  mysql_db:
    name: "{{ database_name }}"
    state: present

- name: Create WordPress MySQL user
  mysql_user:
    name: "{{ database_user }}"
    host: localhost
    password: "{{ database_password }}"
    priv: "{{ database_name }}.*:ALL"

- name: Create wp-config
  template:
    src: wp-config.php.j2
    dest: /var/www/book.example.com/wp-config.php

- name: Does the database exist?
  command: mysql -u root {{ database_name }} -e "SELECT ID FROM {{ database_user }}.wp_users LIMIT 1;"
  register: db_exist
  ignore_errors: true

- name: Copy WordPress DB
  template:
    src: wp-database.sql.j2
    dest: /tmp/wp-database.sql
  when: db_exist.rc > 0

- name: Import WordPress DB
  mysql_db:
    target: /tmp/wp-database.sql
    state: import
    name: "{{ database_name }}"
  when: db_exist.rc > 0
