---

- name: ping
  hosts: wordpress
  become: yes
  tasks:
    - name: Ping de l ensemble des machines cibles
      ping:

- name: Installation de wordpress
  hosts: wordpress
  become: yes
  roles:
    - role: wp.wordpress
