---

- name: ping
  hosts: wordpress
  become: yes
  tasks:
    - name: Ping de l ensemble des machines cibles
      ping:

#Outils
- name: Installation des outils sur le serveur cible en pre-requis
  hosts: wordpress
  become: yes
  tasks:
    - name: Install required tools
      apt:
        name:
          - unzip
        state: present

- name: Appel des roles d installation des dependances et de wordpress
  hosts: wordpress
  become: yes
  roles:
    - role: wp.php
    - role: wp.mysql
    - role: wp.nginx
    - role: wp.wordpress
      database_name: wordpress_test
      database_user: wordpress
      database_password: bananas1234
